# fly.toml app configuration file generated for agent-ki-frontend on 2025-06-28T21:05:20+02:00

app = "agent-ki-frontend"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile.frontend"

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_BACKEND_URL = "https://agent-ki-backend.fly.dev"

[build.args]
  NEXT_PUBLIC_BACKEND_URL = "https://agent-ki-backend.fly.dev"
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
